name = "astro"
pages_build_output_dir = "dist"
compatibility_date = "2026-07-29"

# 🔑 开启 Node.js 原生模块兼容（解决 node:stream 报错）
node_compat = true
compatibility_flags = [ "nodejs_compat" ]

# KV 命名空间绑定
[[kv_namespaces]]
binding = "ADMIN_KV"
id = "ce1325de77914f0c808ba79a06356909"
