name = "astro"
pages_build_output_dir = "dist"
compatibility_date = "2026-07-29"

# 🔑 仅使用 compatibility_flags，不要加 node_compat
compatibility_flags = [ "nodejs_compat" ]

# KV 命名空间绑定
[[kv_namespaces]]
binding = "ADMIN_KV"
id = "ce1325de77914f0c808ba79a06356909"
